<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaginasTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('paginas')->insert([
            [
                'id' => 1,
                'icone' => 'fas fa-chart-area',
                'titulo' => 'Dashboard',
                'slug' => 'dashboard',
                'visualizar' => 'sim',
                'criar' => 'nao',
                'editar' => 'nao',
                'deletar' => 'nao',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'icone' => 'fas fa-table',
                'titulo' => 'Relatórios',
                'slug' => 'relatorios',
                'visualizar' => 'sim',
                'criar' => 'nao',
                'editar' => 'nao',
                'deletar' => 'nao',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'icone' => 'fas fa-calendar-minus',
                'titulo' => 'Calendário',
                'slug' => 'calendarios',
                'visualizar' => 'sim',
                'criar' => 'nao',
                'editar' => 'nao',
                'deletar' => 'nao',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'icone' => 'fas fa-building',
                'titulo' => 'Franquias',
                'slug' => 'franquias',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'icone' => 'fas fa-user',
                'titulo' => 'Usuários',
                'slug' => 'usuarios',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'icone' => 'fas fa-user',
                'titulo' => 'Clientes',
                'slug' => 'clientes',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'icone' => 'fas fa-shopping-cart',
                'titulo' => 'Pedidos',
                'slug' => 'pedidos',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'nao',
                'deletar' => 'nao',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'icone' => 'fas fa-shopping-bag',
                'titulo' => 'Produtos',
                'slug' => 'produtos',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'icone' => 'fas fa-boxes',
                'titulo' => 'Estoque',
                'slug' => 'estoque',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'icone' => 'fas fa-barcode',
                'titulo' => 'Cupons',
                'slug' => 'cupons',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'icone' => 'fas fa-comments',
                'titulo' => 'Perguntas Frequentes',
                'slug' => 'perguntas_frequentes',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'icone' => 'fas fa-info-circle',
                'titulo' => 'Depoimentos',
                'slug' => 'depoimentos',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'icone' => 'fas fa-question',
                'titulo' => 'Dúvidas Frequentes',
                'slug' => 'duvidas',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'icone' => 'fas fa-map-marker-alt',
                'titulo' => 'Regiões Atendidas',
                'slug' => 'regiao_atendida',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'icone' => 'fas fa-map-marker-alt',
                'titulo' => 'CEPs Bloqueados',
                'slug' => 'cep_bloqueados',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'icone' => 'fas fa-images',
                'titulo' => 'Banners',
                'slug' => 'banners',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'icone' => 'fas fa-envelope',
                'titulo' => 'Formulários',
                'slug' => 'formulario_contato',
                'visualizar' => 'sim',
                'criar' => 'nao',
                'editar' => 'nao',
                'deletar' => 'nao',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'icone' => null,
                'titulo' => 'Configurações',
                'slug' => 'configuracoes',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'icone' => null,
                'titulo' => 'Marcas',
                'slug' => 'marcas',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'icone' => null,
                'titulo' => 'Agenda',
                'slug' => 'agenda',
                'visualizar' => 'sim',
                'criar' => 'sim',
                'editar' => 'sim',
                'deletar' => 'sim',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ]
        ]);
    }
}
